# -*- coding: utf-8 -*-
"""GenAI_paperFIXED (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1piP8ipFr9f9kJYUrWinB4tIAewVFr1yz
"""

#cell 1
!pip install -q transformers datasets sentence-transformers scikit-learn matplotlib gradio accelerate evaluate nltk biopython

# CELL 2
import os, math, json, re, random
import torch
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import nltk
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

from datasets import load_dataset
from transformers import (
    GPT2Tokenizer, GPT2LMHeadModel,
    BertTokenizer, BertForSequenceClassification,
    Trainer, TrainingArguments, EarlyStoppingCallback
)
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.calibration import calibration_curve
from sentence_transformers import SentenceTransformer, util
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.tokenize import sent_tokenize
from torch.utils.data import DataLoader
from google.colab import drive

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("WARNING: No GPU — Runtime > Change runtime type > GPU")

# CELL 2B — GLOBAL SEEDING
import random as _random
import numpy as _np
import torch as _torch

SEED = 42

def seed_everything(seed=SEED):
    """Reset every RNG (python random, numpy, torch CPU+CUDA) to a fixed state.
    Call this immediately before ANY stochastic operation (sampling generation,
    random.choice/shuffle, train/val splitting) so that operation is reproducible
    regardless of how many random calls happened earlier in the session."""
    _random.seed(seed)
    _np.random.seed(seed)
    _torch.manual_seed(seed)
    if _torch.cuda.is_available():
        _torch.cuda.manual_seed_all(seed)

seed_everything()
print(f"Global seed set to {SEED} — all RNGs (python/numpy/torch/cuda) synced.")

# CELL 3
drive.mount('/content/drive')

GPT_MODEL_PATH  = "/content/drive/MyDrive/biomedical_gpt_v2"
DISC_MODEL_PATH = "/content/drive/MyDrive/biomedical_discriminator_v3"
RESULTS_PATH    = "/content/drive/MyDrive/biomedical_results_v3"

os.makedirs(RESULTS_PATH, exist_ok=True)
print("Paths ready.")
print("GPT  :", GPT_MODEL_PATH)
print("DISC :", DISC_MODEL_PATH)

#cell-4
gpt_trained  = os.path.exists(os.path.join(GPT_MODEL_PATH,  "config.json"))
disc_trained = os.path.exists(os.path.join(DISC_MODEL_PATH, "config.json"))

print("=" * 55)
print(f"  GPT-2         : {'YES ✅  will LOAD' if gpt_trained  else 'NO  ❌  MISSING'}")
print(f"  BERT v3       : {'YES ✅  will LOAD' if disc_trained else 'NO  ❌  will TRAIN'}")
print("=" * 55)

# CELL 5
print("Loading PubMed dataset...")
dataset = load_dataset("ccdv/pubmed-summarization", split="train")

CHUNK_SIZE = 200

def clean_text(text):
    text = text.replace("\n"," ").replace("\t"," ")
    return re.sub(r'\s+', ' ', text).strip()

def chunk_text(text, size=CHUNK_SIZE):
    words = text.split()
    return [" ".join(words[i:i+size]) for i in range(0, len(words), size)]

all_texts = []
for i, article in enumerate(dataset["article"][:15000]):
    chunks = chunk_text(clean_text(article))
    all_texts.extend(chunks)
    if (i+1) % 3000 == 0:
        print(f"  Processed {i+1}/15000 articles...")

all_texts = [t for t in all_texts if len(t.split()) >= 50]
all_abstracts = [clean_text(a) for a in dataset["abstract"][:15000] if len(a.strip()) > 100]

print(f"Total chunks  : {len(all_texts)}")
print(f"RAG abstracts : {len(all_abstracts)}")

# CELL 6
gpt_tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
gpt_tokenizer.pad_token = gpt_tokenizer.eos_token

class GPTDataset(torch.utils.data.Dataset):
    def __init__(self, texts, tokenizer, max_len=256):
        self.encodings = tokenizer(
            texts, truncation=True, padding="max_length",
            max_length=max_len, return_tensors=None
        )
    def __len__(self): return len(self.encodings["input_ids"])
    def __getitem__(self, idx):
        ids  = torch.tensor(self.encodings["input_ids"][idx])
        mask = torch.tensor(self.encodings["attention_mask"][idx])
        return {"input_ids": ids, "attention_mask": mask, "labels": ids.clone()}

print("GPT-2 tokenizer ready ✅")

# CELL 7
if gpt_trained:
    print("Loading GPT-2 from Drive...")
    gpt_model     = GPT2LMHeadModel.from_pretrained(GPT_MODEL_PATH)
    gpt_tokenizer = GPT2Tokenizer.from_pretrained(GPT_MODEL_PATH)
    gpt_model.to(device)
    print("GPT-2 loaded ✅")
else:
    print("ERROR: GPT-2 model not found in Drive!")
    print("Please check that biomedical_gpt_v2 folder exists in your Drive.")

# CELL 8
def generate_biomedical_text(prompt, max_length=250, seed=SEED):
    seed_everything(seed)
    gpt_model.eval()
    inputs = gpt_tokenizer(prompt, return_tensors="pt").to(device)
    with torch.no_grad():
        outputs = gpt_model.generate(
            **inputs,
            max_length           = max_length,
            temperature          = 0.85,
            top_k                = 50,
            top_p                = 0.92,
            do_sample            = True,
            repetition_penalty   = 1.3,
            no_repeat_ngram_size = 3
        )
    return gpt_tokenizer.decode(outputs[0], skip_special_tokens=True)

test = generate_biomedical_text("Recent advances in cancer immunotherapy suggest")
print("Generation test:")
print(test[:300])

# CELL 9
disc_data_path = "/content/drive/MyDrive/biomedical_results_v2/discriminator_data_v2.csv"

if os.path.exists(disc_data_path):
    print("Loading saved discriminator data...")
    df = pd.read_csv(disc_data_path)
    disc_texts  = list(df["text"])
    disc_labels = list(df["label"])
    print(f"Loaded {len(disc_texts)} samples ✅")
else:
    print("ERROR: discriminator_data_v2.csv not found!")
    print("Please check /content/drive/MyDrive/biomedical_results_v2/")

# CELL 10


import random


MEDICAL_SUBSTITUTIONS = {
    "cancer": ["tumor", "carcinoma", "malignancy", "neoplasm"],
    "patients": ["subjects", "participants", "individuals", "cases"],
    "treatment": ["therapy", "intervention", "procedure", "regimen"],
    "protein": ["enzyme", "receptor", "molecule", "compound"],
    "gene": ["allele", "locus", "sequence", "marker"],
    "cells": ["tissue", "organisms", "specimens", "samples"],
    "disease": ["condition", "disorder", "syndrome", "pathology"],
    "clinical": ["medical", "therapeutic", "diagnostic", "experimental"],
    "significant": ["notable", "substantial", "considerable", "marginal"],
    "increased": ["elevated", "enhanced", "reduced", "altered"],
    "immune": ["inflammatory", "cellular", "humoral", "innate"],
    "therapy": ["treatment", "intervention", "medication", "surgery"],
    "survival": ["mortality", "prognosis", "outcome", "recurrence"],
    "mutations": ["variants", "polymorphisms", "alterations", "deletions"],
    "inhibitor": ["activator", "blocker", "agonist", "antagonist"],
}

def create_adversarial_example(text):
    """Corrupt real text by swapping medical terms — creates hard negatives."""
    words = text.split()
    num_swaps = max(1, len(words) // 30)
    swapped = 0

    for i, word in enumerate(words):
        word_lower = word.lower().rstrip('.,;:')
        if word_lower in MEDICAL_SUBSTITUTIONS and swapped < num_swaps:
            replacement = random.choice(MEDICAL_SUBSTITUTIONS[word_lower])
            words[i] = replacement
            swapped += 1


    for i, word in enumerate(words):
        if word.replace('.','').replace('%','').isdigit() and random.random() < 0.3:
            try:
                num = float(word.replace('%',''))
                words[i] = str(round(num * random.uniform(0.5, 2.0), 1))
            except:
                pass

    return " ".join(words)


seed_everything(SEED)
print("Creating adversarial examples from real PubMed text...")
real_texts_for_adv = [t for t in all_texts[:6000] if len(t.split()) >= 80]
adversarial_examples = []

for i, text in enumerate(real_texts_for_adv[:2000]):
    adv = create_adversarial_example(text)
    adversarial_examples.append(adv)
    if (i+1) % 500 == 0:
        print(f"  Created {i+1}/2000 adversarial examples...")

print(f"Adversarial examples created: {len(adversarial_examples)}")
print(f"\nOriginal : {real_texts_for_adv[0][:200]}")
print(f"\nCorrupted: {adversarial_examples[0][:200]}")

# CELL 11


real_samples = [t for t, l in zip(disc_texts, disc_labels) if l == 1][:3000]
gpt_samples  = [t for t, l in zip(disc_texts, disc_labels) if l == 0][:2000]


all_negatives = gpt_samples + adversarial_examples[:2000]


final_texts  = real_samples + all_negatives
final_labels = [1]*len(real_samples) + [0]*len(all_negatives)


seed_everything(SEED)
combined = list(zip(final_texts, final_labels))
random.shuffle(combined)
final_texts, final_labels = zip(*combined)
final_texts  = list(final_texts)
final_labels = list(final_labels)

print(f"Real samples        : {len(real_samples)}")
print(f"GPT-2 generated     : {len(gpt_samples)}")
print(f"Adversarial examples: {len(adversarial_examples[:2000])}")
print(f"Total dataset       : {len(final_texts)}")
print(f"Label balance       : {sum(final_labels)} real / {len(final_labels)-sum(final_labels)} fake")

# CELL 12
bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

class DiscDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=256):
        self.encodings = tokenizer(
            texts, truncation=True, padding=True, max_length=max_len
        )
        self.labels = labels
    def __len__(self): return len(self.labels)
    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item


d_train_texts, d_val_texts, d_train_labels, d_val_labels = train_test_split(
    final_texts, final_labels,
    test_size=0.15, stratify=final_labels, random_state=42
)

disc_train_dataset = DiscDataset(d_train_texts, d_train_labels, bert_tokenizer)
disc_val_dataset   = DiscDataset(d_val_texts,   d_val_labels,   bert_tokenizer)

print(f"Train: {len(d_train_texts)} | Val: {len(d_val_texts)}")
print(f"Train balance: {sum(d_train_labels)} real / {len(d_train_labels)-sum(d_train_labels)} fake")

# CELL 13
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    acc = accuracy_score(labels, preds)
    return {"accuracy": acc}

if not disc_trained:
    print("Training BERT discriminator with adversarial examples...")
    disc_model = BertForSequenceClassification.from_pretrained(
        "bert-base-uncased",
        num_labels                   = 2,
        hidden_dropout_prob          = 0.3,
        attention_probs_dropout_prob = 0.3
    )
    disc_model.to(device)

    disc_args = TrainingArguments(
        output_dir                  = "./disc_v3_checkpoints",
        num_train_epochs            = 4,
        per_device_train_batch_size = 16,
        per_device_eval_batch_size  = 32,
        learning_rate               = 1e-5,
        weight_decay                = 0.05,
        warmup_ratio                = 0.15,
        lr_scheduler_type           = "cosine",
        fp16                        = True,
        eval_strategy               = "epoch",
        save_strategy               = "epoch",
        load_best_model_at_end      = True,
        metric_for_best_model       = "accuracy",
        greater_is_better           = True,
        logging_steps               = 100,
        save_total_limit            = 2,
        report_to                   = "none"
    )

    disc_trainer = Trainer(
        model           = disc_model,
        args            = disc_args,
        train_dataset   = disc_train_dataset,
        eval_dataset    = disc_val_dataset,
        compute_metrics = compute_metrics,
        callbacks       = [EarlyStoppingCallback(early_stopping_patience=2)]
    )

    disc_trainer.train()
    disc_trainer.save_model(DISC_MODEL_PATH)
    bert_tokenizer.save_pretrained(DISC_MODEL_PATH)
    print("BERT v3 saved to Drive ✅")

else:
    print("BERT v3 already trained — loading from Drive...")
    disc_model     = BertForSequenceClassification.from_pretrained(DISC_MODEL_PATH)
    bert_tokenizer = BertTokenizer.from_pretrained(DISC_MODEL_PATH)
    disc_model.to(device)
    print("BERT v3 loaded ✅")

# CELL 14
hnm_done_path = f"{RESULTS_PATH}/hnm_done.txt"

if os.path.exists(hnm_done_path):
    print("Hard negative mining already done — loading model from Drive...")
    disc_model = BertForSequenceClassification.from_pretrained(DISC_MODEL_PATH)
    bert_tokenizer = BertTokenizer.from_pretrained(DISC_MODEL_PATH)
    disc_model.to(device)
    print("Model loaded ✅ Skipping retraining.")

else:
    print("Running hard negative mining...")

    disc_model.eval()
    hard_texts, hard_labels = [], []
    uncertain_count = 0

    with torch.no_grad():
        for text, label in zip(d_train_texts[:3000], d_train_labels[:3000]):
            inputs = bert_tokenizer(
                text, return_tensors="pt", truncation=True,
                padding=True, max_length=256
            ).to(device)
            outputs = disc_model(**inputs)
            probs   = torch.softmax(outputs.logits, dim=1)
            confidence = probs.max().item()

            if confidence < 0.70:
                hard_texts.append(text)
                hard_labels.append(label)
                uncertain_count += 1

    print(f"Hard/uncertain samples found: {uncertain_count}")

    if len(hard_texts) > 50:
        augmented_texts  = d_train_texts + hard_texts + hard_texts
        augmented_labels = list(d_train_labels) + hard_labels + hard_labels

        aug_dataset = DiscDataset(augmented_texts, augmented_labels, bert_tokenizer)

        print(f"Retraining with hard negatives ({len(augmented_texts)} samples)...")

        hard_args = TrainingArguments(
            output_dir                  = "./disc_hard_checkpoints",
            num_train_epochs            = 2,
            per_device_train_batch_size = 16,
            per_device_eval_batch_size  = 32,
            learning_rate               = 5e-6,
            weight_decay                = 0.05,
            fp16                        = True,
            eval_strategy               = "epoch",
            save_strategy               = "epoch",
            load_best_model_at_end      = True,
            metric_for_best_model       = "accuracy",
            greater_is_better           = True,
            logging_steps               = 50,
            save_total_limit            = 1,
            report_to                   = "none"
        )

        hard_trainer = Trainer(
            model           = disc_model,
            args            = hard_args,
            train_dataset   = aug_dataset,
            eval_dataset    = disc_val_dataset,
            compute_metrics = compute_metrics,
        )

        hard_trainer.train()
        hard_trainer.save_model(DISC_MODEL_PATH)
        bert_tokenizer.save_pretrained(DISC_MODEL_PATH)
        print("Hard-mined model saved to Drive ✅")

    else:
        print("Model already handles hard cases well — skipping retraining")


    with open(hnm_done_path, 'w') as f:
        f.write("done")
    print("Hard negative mining flagged as complete ✅")

# CELL 15

print("Calibrating confidence scores...")

disc_model.eval()
all_logits, all_labels_cal = [], []

with torch.no_grad():
    for text, label in zip(d_val_texts[:500], d_val_labels[:500]):
        inputs = bert_tokenizer(
            text, return_tensors="pt", truncation=True,
            padding=True, max_length=256
        ).to(device)
        outputs = disc_model(**inputs)
        all_logits.append(outputs.logits.cpu())
        all_labels_cal.append(label)

all_logits_t = torch.cat(all_logits, dim=0)
all_labels_t = torch.tensor(all_labels_cal)


best_temp, best_nll = 1.0, float('inf')
for temp in [0.5, 0.75, 1.0, 1.25, 1.5, 2.0, 2.5]:
    scaled = all_logits_t / temp
    nll = torch.nn.CrossEntropyLoss()(scaled, all_labels_t).item()
    if nll < best_nll:
        best_nll  = nll
        best_temp = temp

print(f"Optimal calibration temperature: {best_temp}")
print(f"(Temperature > 1.0 means model was overconfident — now corrected)")

def detect_hallucination(text, temperature=best_temp):
    """Calibrated hallucination detection with temperature scaling."""
    disc_model.eval()
    inputs = bert_tokenizer(
        text, return_tensors="pt", truncation=True,
        padding=True, max_length=256
    ).to(device)
    with torch.no_grad():
        outputs = disc_model(**inputs)
    scaled_logits = outputs.logits / temperature
    probs         = torch.softmax(scaled_logits, dim=1)
    real_score    = round(probs[0][1].item(), 4)
    hall_score    = round(probs[0][0].item(), 4)
    return real_score, hall_score

def detect_sentence_level(text, temperature=best_temp):
    """Score each sentence individually."""
    sentences = sent_tokenize(text)
    results   = []
    for sent in sentences:
        if len(sent.split()) < 5:
            continue
        r, h = detect_hallucination(sent, temperature)
        label = "HIGH" if h > 0.6 else ("MODERATE" if h > 0.35 else "LOW")
        results.append({"sentence": sent, "real": r, "risk": h, "label": label})
    return results

def risk_label(h):
    if h > 0.6:  return "🔴 HIGH Hallucination Risk"
    if h > 0.35: return "🟡 MODERATE Hallucination Risk"
    return "🟢 LOW Hallucination Risk"


sample = generate_biomedical_text("Recent advances in cancer immunotherapy suggest")
r, h   = detect_hallucination(sample)
print(f"\nCalibrated test — Real: {r} | Hall Risk: {h}")
print(risk_label(h))

# CELL 16
semantic_model = SentenceTransformer('all-MiniLM-L6-v2')

def calculate_perplexity(text):
    gpt_model.eval()
    inputs = gpt_tokenizer(text, return_tensors="pt", truncation=True, max_length=256).to(device)
    with torch.no_grad():
        outputs = gpt_model(**inputs, labels=inputs["input_ids"])
    return round(math.exp(min(outputs.loss.item(), 20)), 2)

def calculate_bleu(reference, hypothesis):
    smoother = SmoothingFunction().method1
    return round(sentence_bleu([reference.split()], hypothesis.split(), smoothing_function=smoother), 4)

def calculate_semantic_similarity(t1, t2):
    e1 = semantic_model.encode(t1, convert_to_tensor=True)
    e2 = semantic_model.encode(t2, convert_to_tensor=True)
    return round(util.cos_sim(e1, e2).item(), 4)

_EVAL_STOPWORDS = {"recent","advances","suggest","studies","show","indicate",
                    "has","have","the","of","in","and","a","an","that","for",
                    "been","which","with","from","this","these","their","role",
                    "approaches","applications","treatments","based","novel",
                    "early","detection","disorders"}

def _extract_keywords(prompt, k=4):
    words = [w.strip(".,;:").lower() for w in prompt.split()]
    words = [w for w in words if w not in _EVAL_STOPWORDS and len(w) > 3]
    return words[:k]

def find_topical_reference(prompt, corpus, fallback_idx=0):
    """Return the chunk in `corpus` with the most keyword hits for `prompt`'s topic.
    Falls back to the first chunk if nothing matches (should be rare)."""
    keywords = _extract_keywords(prompt)
    if not keywords:
        return corpus[fallback_idx]

    best_idx, best_hits = None, 0
    for idx, chunk in enumerate(corpus):
        chunk_lower = chunk.lower()
        hits = sum(1 for kw in keywords if kw in chunk_lower)
        if hits > best_hits:
            best_hits, best_idx = hits, idx
            if best_hits == len(keywords):
                break
    return corpus[best_idx] if best_idx is not None else corpus[fallback_idx]
# ------------------------------------------------------------------------

test_prompts = [
    "Recent advances in cancer immunotherapy suggest",
    "Studies on Alzheimer's disease have shown that",
    "The role of gut microbiota in metabolic syndrome",
    "Gene therapy approaches for rare genetic disorders",
    "Machine learning applications in medical imaging diagnosis",
    "CRISPR-based treatments for inherited blood disorders",
    "Novel biomarkers for early detection of pancreatic cancer"
]

seed_everything(SEED)
print("=" * 65)
results = []
for i, prompt in enumerate(test_prompts):
    ref  = find_topical_reference(prompt, all_texts, fallback_idx=i * 200)
    gen  = generate_biomedical_text(prompt)
    ppl  = calculate_perplexity(gen)
    bleu = calculate_bleu(ref, gen)
    sem  = calculate_semantic_similarity(ref, gen)
    r, h = detect_hallucination(gen)
    results.append({"Prompt": prompt[:45], "Perplexity": ppl,
                    "BLEU": bleu, "Semantic Sim": sem,
                    "Real Score": r, "Hall Risk": h})
    print(f"Prompt: {prompt[:50]}")
    print(f"  PPL={ppl}  BLEU={bleu}  Sem={sem}  Real={r}  Risk={h}  {risk_label(h)}")

results_df = pd.DataFrame(results)
results_df.to_csv(f"{RESULTS_PATH}/evaluation_results_v3.csv", index=False)
print("\nResults saved ✅")

# Balanced 500-sample evaluation — matches paper
real_val = [(t, l) for t, l in zip(d_val_texts, d_val_labels) if l == 1]
fake_val = [(t, l) for t, l in zip(d_val_texts, d_val_labels) if l == 0]

seed_everything(SEED)

eval_samples = real_val[:250] + fake_val[:250]
random.shuffle(eval_samples)

preds, trues = [], []

for text, label in eval_samples:
    r, h = detect_hallucination(text)
    preds.append(1 if r > h else 0)
    trues.append(label)

acc = accuracy_score(trues, preds)

print(f"Discriminator Accuracy: {acc*100:.2f}%")
print(classification_report(
    trues, preds,
    target_names=["Hallucinated", "Real"]
))

# CELL 17B
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(trues, preds, labels=[0, 1])
fig, ax = plt.subplots(figsize=(6, 6))
im = ax.imshow(cm, cmap="Blues")
ax.set_title("Discriminator Confusion Matrix", fontsize=16, fontweight='bold')
ax.set_xticks([0, 1]); ax.set_xticklabels(["Hallucinated", "Real"])
ax.set_yticks([0, 1]); ax.set_yticklabels(["Hallucinated", "Real"])
ax.set_xlabel("Predicted label")
ax.set_ylabel("True label")

thresh = cm.max() / 2
for i in range(2):
    for j in range(2):
        ax.text(j, i, str(cm[i, j]), ha="center", va="center",
                color="white" if cm[i, j] > thresh else "#1a3c7a", fontsize=14)

plt.tight_layout()
cm_path = f"{RESULTS_PATH}/confusion_matrix_v3.png"
plt.savefig(cm_path, dpi=150, bbox_inches='tight')
plt.show()

print(f"True label counts in this eval set — Hallucinated: {cm[0].sum()}, Real: {cm[1].sum()}")
if cm[0].sum() == 0:
    print("\n⚠️  WARNING: 0 'Hallucinated' true labels in this batch — the validation")
    print("    slice being evaluated is not actually balanced. Check d_val_labels[:500]")
    print("    composition (e.g. print(sum(d_val_labels[:500]), len(d_val_labels[:500]))")
    print("    before trusting this matrix / any accuracy computed from it.)")

# CELL 18
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle("Biomedical Hallucination Detection v3 — Patent-Level Results", fontsize=14, fontweight='bold')

ax1 = axes[0, 0]
metrics_avg = results_df[["BLEU","Semantic Sim","Real Score","Hall Risk"]].mean()
colors = ["#4CAF50","#2196F3","#FF9800","#F44336"]
bars = ax1.bar(metrics_avg.index, metrics_avg.values, color=colors, edgecolor='white')
ax1.set_title("Average Evaluation Metrics", fontweight='bold')
ax1.set_ylim(0, 1)
for bar, val in zip(bars, metrics_avg.values):
    ax1.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.01, f"{val:.3f}", ha='center', fontsize=9)
ax1.tick_params(axis='x', rotation=20)

ax2 = axes[0, 1]
ax2.bar(range(len(results_df)), results_df["Perplexity"], color="#9C27B0", edgecolor='white')
ax2.set_title("Perplexity per Prompt (lower=better)", fontweight='bold')
ax2.set_xticks(range(len(results_df)))
ax2.set_xticklabels([f"P{i+1}" for i in range(len(results_df))])
ax2.set_ylabel("Perplexity")

ax3 = axes[0, 2]
x = np.arange(len(results_df))
ax3.bar(x-0.2, results_df["Real Score"], 0.4, label="Real Score", color="#4CAF50", edgecolor='white')
ax3.bar(x+0.2, results_df["Hall Risk"],  0.4, label="Hall Risk",  color="#F44336", edgecolor='white')
ax3.set_title("Real vs Hallucination Scores", fontweight='bold')
ax3.set_xticks(x); ax3.set_xticklabels([f"P{i+1}" for i in range(len(results_df))])
ax3.legend(); ax3.set_ylim(0, 1)

ax4 = axes[1, 0]
correct = int(acc * 500)
ax4.pie([correct, 500-correct], labels=["Correct","Incorrect"],
        colors=["#4CAF50","#F44336"], autopct='%1.1f%%', startangle=90)
ax4.set_title(f"Discriminator Accuracy ({acc*100:.1f}%)", fontweight='bold')

ax5 = axes[1, 1]
ax5.scatter(results_df["BLEU"], results_df["Semantic Sim"],
            c=results_df["Hall Risk"], cmap='RdYlGn_r', s=150, edgecolors='gray', zorder=3)
for i, row in results_df.iterrows():
    ax5.annotate(f"P{i+1}", (row["BLEU"], row["Semantic Sim"]), fontsize=9)
ax5.set_xlabel("BLEU Score"); ax5.set_ylabel("Semantic Similarity")
ax5.set_title("BLEU vs Semantic Sim (color=hall risk)", fontweight='bold')

ax6 = axes[1, 2]
risk_counts = {"LOW": 0, "MODERATE": 0, "HIGH": 0}
for _, row in results_df.iterrows():
    h = row["Hall Risk"]
    if h > 0.6: risk_counts["HIGH"] += 1
    elif h > 0.35: risk_counts["MODERATE"] += 1
    else: risk_counts["LOW"] += 1
ax6.bar(risk_counts.keys(), risk_counts.values(), color=["#4CAF50","#FF9800","#F44336"], edgecolor='white')
ax6.set_title("Hallucination Risk Distribution", fontweight='bold')
ax6.set_ylabel("Count")

plt.tight_layout()
graph_path = f"{RESULTS_PATH}/results_v3.png"
plt.savefig(graph_path, dpi=150, bbox_inches='tight')
plt.show()
print(f"Graphs saved ✅")

# CELL 19
from Bio import Entrez
Entrez.email = "research@biomedical.ai"

def fetch_pubmed_abstracts(query, max_results=3):
    """Fetch real verified PubMed abstracts via NCBI Entrez API."""
    try:
        handle  = Entrez.esearch(db="pubmed", term=query, retmax=max_results, sort="relevance")
        record  = Entrez.read(handle)
        ids     = record["IdList"]
        if not ids:
            return ["No PubMed results found for this query."]
        handle  = Entrez.efetch(db="pubmed", id=",".join(ids), rettype="abstract", retmode="text")
        raw     = handle.read()
        abstracts = [a.strip() for a in raw.split("\n\n") if len(a.strip()) > 100]
        return abstracts[:max_results]
    except Exception as e:
        return [f"PubMed retrieval error: {str(e)}"]

def extract_topic(prompt):
    stopwords = {"recent","advances","suggest","studies","show","indicate",
                 "has","have","the","of","in","and","a","an","that","for",
                 "been","which","with","from","this","these","their"}
    words = [w for w in prompt.lower().split() if w not in stopwords and len(w) > 3]
    return " ".join(words[:5])


topic = extract_topic("Recent advances in cancer immunotherapy suggest")
print(f"Testing RAG for: '{topic}'")
abstracts = fetch_pubmed_abstracts(topic, max_results=3)
for i, a in enumerate(abstracts):
    print(f"\n--- Real PubMed Abstract {i+1} ---")
    print(a[:400])

# CELL 20
import gradio as gr

def full_analysis(prompt):
    if not prompt.strip():
        return "Please enter a prompt.", "", "", "", "", ""

    seed_everything(SEED)
    gen_text = generate_biomedical_text(prompt, max_length=300)


    r, h = detect_hallucination(gen_text)
    ppl  = calculate_perplexity(gen_text)
    risk = risk_label(h)


    sent_scores = detect_sentence_level(gen_text)
    sent_report = ""
    for s in sent_scores:
        icon = "🔴" if s["label"]=="HIGH" else ("🟡" if s["label"]=="MODERATE" else "🟢")
        sent_report += f"{icon} [Risk: {s['risk']:.2f}] {s['sentence']}\n\n"


    score_bar = (
        f"Real Score         {'█'*int(r*20):<20} {r:.2%}\n"
        f"Hallucination Risk {'█'*int(h*20):<20} {h:.2%}\n"
        f"Perplexity         {ppl} (lower = more fluent)\n"
        f"Calibration Temp   {best_temp} (corrects overconfidence)"
    )


    if h > 0.35:
        topic     = extract_topic(prompt)
        abstracts = fetch_pubmed_abstracts(topic, max_results=3)
        rag_out   = f"Real verified PubMed sources for '{topic}':\n\n"
        for i, a in enumerate(abstracts):
            rag_out += f"📄 Source {i+1}:\n{a[:500]}\n\n"
    else:
        rag_out = "✅ Hallucination risk is LOW — generated text appears statistically reliable.\n\nNo retrieval needed."

    return gen_text, risk, score_bar, sent_report, rag_out, f"Real={r:.4f} | Risk={h:.4f} | PPL={ppl}"

with gr.Blocks(title="Biomedical Hallucination Detector v3", theme=gr.themes.Soft()) as demo:
    gr.Markdown("""
    # 🧬 Biomedical Text Generation + Hallucination Detection
    ### GPT-2 (15k PubMed) | Adversarial BERT | Hard Negative Mining | Confidence Calibration | RAG
    Enter a biomedical prompt to generate research text and get a full hallucination analysis.
    """)

    with gr.Row():
        with gr.Column(scale=2):
            prompt_box = gr.Textbox(
                label="Biomedical Research Prompt",
                placeholder="e.g. Recent advances in cancer immunotherapy suggest...",
                lines=2
            )
            btn = gr.Button("Generate & Analyze", variant="primary", size="lg")
        with gr.Column(scale=1):
            risk_out   = gr.Textbox(label="Overall Risk Level",   interactive=False)
            scores_out = gr.Textbox(label="Scores Summary",       interactive=False)

    with gr.Row():
        gen_out  = gr.Textbox(label="Generated Biomedical Text", lines=7, interactive=False)
        bar_out  = gr.Textbox(label="Score Visualization",       lines=4, interactive=False)

    sent_out = gr.Textbox(
        label="Sentence-level Hallucination Breakdown (each sentence scored individually)",
        lines=8, interactive=False
    )
    rag_out = gr.Textbox(
        label="Real PubMed Sources — Retrieved automatically when risk is MODERATE or HIGH",
        lines=8, interactive=False
    )

    gr.Examples(
        examples=[
            ["Recent advances in cancer immunotherapy suggest"],
            ["The role of gut microbiota in metabolic syndrome"],
            ["Gene therapy for rare genetic disorders has shown"],
            ["CRISPR applications in treating sickle cell disease"],
            ["Machine learning for early detection of Alzheimer's disease"],
            ["Novel drug targets in type 2 diabetes treatment"],
        ],
        inputs=prompt_box
    )

    btn.click(
        fn      = full_analysis,
        inputs  = [prompt_box],
        outputs = [gen_out, risk_out, bar_out, sent_out, rag_out, scores_out]
    )

demo.launch(share=True)